
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (1, 'want813', '¹ÚÈñÈñ', '1111');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (2, 'want815', '¹Ú¼ºÈñ', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (3, 'kangdw', '°­µ¿¿ø', '3333');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (4, 'want813', '¹ÚÈñÈñ', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (5, 'want815', '¹Ú¼ºÈñ', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (6, 'kangdw', '°­µ¿¿ø', '3333');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (7, 'want813', '¹ÚÈñÈñ', '1111');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (8, 'want815', '¹Ú¼ºÈñ', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (9, 'kangdw', '°­µ¿¿ø', '3333');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (10, 'want813', '¹ÚÈñÈñ', '1111');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (11, 'want815', '¹Ú¼ºÈñ', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (12, 'kangdw', '°­µ¿¿ø', '3333');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (13, 'want813', '¹ÚÈñÈñ', '1111');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (14, 'want815', '¹Ú¼ºÈñ', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (15, 'kangdw', '°­µ¿¿ø', '3333');