DROP TABLE USERS IF EXISTS CASCADE;
DROP TABLE USER_POINT IF EXISTS CASCADE;

CREATE TABLE USERS 
(	
	SEQ INTEGER primary key,
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	POINT INTEGER DEFAULT 0
);

CREATE TABLE USER_POINT
(
	USER_POINT_SEQ INTEGER primary key,
	USER_SEQ INTEGER NOT NULL, 
	POINT INTEGER NOT NULL,
	POINT_TYPE VARCHAR(10) NOT NULL,	
	REG_DT DATE NOT NULL
);


