
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (1, 'want813', '박희희', '1111');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (2, 'want815', '박성희', '2222');

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (3, 'kangdw', '강동원', '3333');
