DROP TABLE POST IF EXISTS CASCADE;
DROP TABLE USERS IF EXISTS CASCADE;
DROP TABLE FILE IF EXISTS CASCADE;
DROP TABLE POST_FILE IF EXISTS CASCADE;

CREATE TABLE POST 
(	
	POST_SEQ INTEGER primary key,
	TITLE VARCHAR(50) NOT NULL,
	CONTENTS VARCHAR(4000),
	REG_USR INTEGER NOT NULL,
	REG_DT DATE NOT NULL,
	MOD_USR INTEGER,
	MOD_DT DATE
);

CREATE TABLE USERS 
(	
	SEQ INTEGER primary key,
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE FILE
(
	FL_SEQ INTEGER primary key,
	FL_NM VARCHAR(100) NOT NULL,
	FL_PTH VARCHAR(100) NOT NULL,
	FL_EXT VARCHAR(100) NOT NULL,
	FL_SZ INTEGER DEFAULT 0,
	REG_USR INTEGER NOT NULL,
	REG_DT DATE NOT NULL
);

CREATE TABLE POST_FILE
(
	POST_SEQ INTEGER NOT NULL,
	FL_SEQ INTEGER NOT NULL
);
