
insert into BOARD(POST_ID, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT) values(1, 'HOT PIZZA', 'BIG PIECRUST', 1, SYSDATE, 0, null);
insert into BOARD(POST_ID, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT) values(2, 'COLD PIZZA', 'SMALL PIECRUST', 1, SYSDATE, 0, null);

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (1, 'gosu', '고수', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (2, 'leejw', '이진욱', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (3, 'kangdw', '강동원', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (4, 'mudo1', '유재석', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (5, 'mudo2', '박명수', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (6, 'mudo3', '정준하', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (7, 'mudo4', '정형돈', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (8, 'mudo5', '길', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (9, 'mudo6', '노홍철', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (10, 'mudo7', '하하', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (11, 'SquidwardTentacles', '징징이', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (12, 'MatthewBomer', '닐카프리', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (13, 'JamesMcAvoy', '제임스맥어보이', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (14, 'spongebob', '스폰지밥', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (15, 'PatrickStar', '뚱이', '3333');