
insert into POST(POST_SEQ, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT, UP_POST_SEQ, ODR, LVL) values(1, 'HOT PIZZA', 'BIG PIECRUST', 1, SYSDATE, 0, null, 1, 0, 0);
insert into POST(POST_SEQ, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT, UP_POST_SEQ, ODR, LVL) values(2, 'COLD PIZZA', 'SMALL PIECRUST', 1, SYSDATE, 0, null, 2, 0, 0);
insert into POST(POST_SEQ, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT, UP_POST_SEQ, ODR, LVL) values(3, '주문가능한가요?', 'SMALL PIECRUST', 1, SYSDATE, 0, null, 1, 1, 1);
insert into POST(POST_SEQ, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT, UP_POST_SEQ, ODR, LVL) values(4, '주문가능합니다.', 'SMALL PIECRUST', 1, SYSDATE, 0, null, 1, 2, 2);
insert into POST(POST_SEQ, TITLE, CONTENTS, REG_USR, REG_DT, MOD_USR, MOD_DT, UP_POST_SEQ, ODR, LVL) values(5, '저도 주문합니다.', 'SMALL PIECRUST', 1, SYSDATE, 0, null, 1, 3, 1);

INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (1, 'gosu', '고수', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (2, 'leejw', '이진욱', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (3, 'kangdw', '강동원', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (4, 'mudo1', '유재석', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (5, 'mudo2', '박명수', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (6, 'mudo3', '정준하', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (7, 'mudo4', '정형돈', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (8, 'mudo5', '길', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (9, 'mudo6', '노홍철', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (10, 'mudo7', '하하', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (11, 'SquidwardTentacles', '징징이', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (12, 'MatthewBomer', '닐카프리', '3333');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (13, 'JamesMcAvoy', '제임스맥어보이', '1111');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (14, 'spongebob', '스폰지밥', '2222');
INSERT INTO USERS (SEQ, ID, NAME, PASSWORD) VALUES (15, 'PatrickStar', '뚱이', '3333');

INSERT INTO FILE(FILE_SEQ, FILE_NM, FILE_PTH, FILE_EXT, FILE_SZ, REG_USR, REG_DT) VALUES (1, '리스트', '/file/2011/03/123456789.txt', 'txt', 1234, 1, SYSDATE);
INSERT INTO POST_FILE(POST_SEQ, FILE_SEQ) VALUES (1, 1);